import React from 'react';
import type { ComplianceReport } from '../types';
import ReportCard from './ReportCard';

const PublicReportView: React.FC<{ report: ComplianceReport }> = ({ report }) => {
  return (
    <div className="min-h-screen bg-light flex flex-col">
        <header className="bg-white shadow-sm">
             <div className="container mx-auto px-4 sm:px-6 lg:px-8">
                <div className="flex items-center justify-between h-16">
                    <div className="flex-shrink-0 flex items-center gap-3">
                        <svg className="h-8 w-8 text-accent" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth="2" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                        </svg>
                        <span className="text-2xl font-bold text-slate-dark">Clarity</span>
                    </div>
                </div>
            </div>
        </header>
        <main className="flex-grow container mx-auto p-4 sm:p-6 lg:p-8">
            <div className="max-w-4xl mx-auto">
                <div className="text-center mb-8">
                    <h1 className="text-3xl font-bold text-slate-dark">Shared Compliance Report</h1>
                    <p className="text-slate-light mt-2">This is a read-only view of a report generated by Clarity.</p>
                </div>
                <ReportCard report={report} />
            </div>
        </main>
        <footer className="w-full text-center p-6 bg-white border-t">
            <p className="text-slate-light">Want to run your own compliance checks and generate revisions?</p>
            <a href={window.location.origin} className="text-accent-dark font-bold hover:underline text-lg">
                Try Clarity for Free
            </a>
            <p className="text-xs text-gray-400 mt-4">&copy; 2024 Clarity. All rights reserved.</p>
        </footer>
    </div>
  );
};

export default PublicReportView;